### PR TITLE
Enjfooter

### PR DESCRIPTION
**Pull request by Enoch7744**

### CODE REVIEW

**Review by hinasuleman — APPROVED** [review]
Footer added acknowledged

**Review by cjsutcliffe — CHANGES_REQUESTED** [review]
dont merge straight into main, mege into the feature branch -> dev -> main

**Review by coopsie — CHANGES_REQUESTED** [review]
You need to merge your branch enjfooter into the feature/layout branch, not main. Close this request and create a new pull request please

**Comment by cjsutcliffe** [comment]
closed - reopen as a new PR into the correct feature branch - happy to walk through this with you CS

**Pull request closed without merging**
