### PR TITLE
Feature/mainpage

### PR DESCRIPTION
**Pull request by cjsutcliffe**

### CODE REVIEW

**Review by sobanaq — APPROVED** [review]
Please check conflict in App.js.

**Review by hinasuleman — APPROVED** [review]
Reviewed and approved pull request

**Review by coopsie — APPROVED** [review]
The conflicts seem to be trivial - it looks like you've removed the generic/pre loaded React code which is fine. Go ahead with merge.

**Comment by hinasuleman** [comment]
Go ahead with the merge as this conflict is of little importance and can be resolved

**Pull request merged**
