### PR TITLE
Feature/landingpage

### PR DESCRIPTION
**Pull request by sobanaq**
React router DOM added. Please check.

### CODE REVIEW

**Comment by hannahmullah** [comment]
good to continue

**Comment by coopsie** [comment]
Reviewed and no issues

**Review by hannahmullah — APPROVED** [review]

**Comment by Enoch7744** [comment]
good to continue

**Review by coopsie — COMMENTED** [review]
Reviewed and approved, no issues

**Review by coopsie — APPROVED** [review]
Approved

**Pull request merged**
